//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team34_GP_IFM02B2_2023_WebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRecord", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class UserRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool enabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime userRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                if ((this.enabledField.Equals(value) != true)) {
                    this.enabledField = value;
                    this.RaisePropertyChanged("enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userEmail {
            get {
                return this.userEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.userEmailField, value) != true)) {
                    this.userEmailField = value;
                    this.RaisePropertyChanged("userEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime userReg {
            get {
                return this.userRegField;
            }
            set {
                if ((this.userRegField.Equals(value) != true)) {
                    this.userRegField = value;
                    this.RaisePropertyChanged("userReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRecord", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class CustomerRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool grantRecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord uField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((this.birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fName {
            get {
                return this.fNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fNameField, value) != true)) {
                    this.fNameField = value;
                    this.RaisePropertyChanged("fName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool grantRec {
            get {
                return this.grantRecField;
            }
            set {
                if ((this.grantRecField.Equals(value) != true)) {
                    this.grantRecField = value;
                    this.RaisePropertyChanged("grantRec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lName {
            get {
                return this.lNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lNameField, value) != true)) {
                    this.lNameField = value;
                    this.RaisePropertyChanged("lName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord u {
            get {
                return this.uField;
            }
            set {
                if ((object.ReferenceEquals(this.uField, value) != true)) {
                    this.uField = value;
                    this.RaisePropertyChanged("u");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreRecord", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class StoreRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord uField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string logo {
            get {
                return this.logoField;
            }
            set {
                if ((object.ReferenceEquals(this.logoField, value) != true)) {
                    this.logoField = value;
                    this.RaisePropertyChanged("logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sType {
            get {
                return this.sTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sTypeField, value) != true)) {
                    this.sTypeField = value;
                    this.RaisePropertyChanged("sType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord u {
            get {
                return this.uField;
            }
            set {
                if ((object.ReferenceEquals(this.uField, value) != true)) {
                    this.uField = value;
                    this.RaisePropertyChanged("u");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRecord", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class ProductRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool enabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime prodDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prodPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                if ((this.enabledField.Equals(value) != true)) {
                    this.enabledField = value;
                    this.RaisePropertyChanged("enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime prodDate {
            get {
                return this.prodDateField;
            }
            set {
                if ((this.prodDateField.Equals(value) != true)) {
                    this.prodDateField = value;
                    this.RaisePropertyChanged("prodDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodDesc {
            get {
                return this.prodDescField;
            }
            set {
                if ((object.ReferenceEquals(this.prodDescField, value) != true)) {
                    this.prodDescField = value;
                    this.RaisePropertyChanged("prodDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodId {
            get {
                return this.prodIdField;
            }
            set {
                if ((this.prodIdField.Equals(value) != true)) {
                    this.prodIdField = value;
                    this.RaisePropertyChanged("prodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodName {
            get {
                return this.prodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.prodNameField, value) != true)) {
                    this.prodNameField = value;
                    this.RaisePropertyChanged("prodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prodPrice {
            get {
                return this.prodPriceField;
            }
            set {
                if ((this.prodPriceField.Equals(value) != true)) {
                    this.prodPriceField = value;
                    this.RaisePropertyChanged("prodPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                if ((this.storeIdField.Equals(value) != true)) {
                    this.storeIdField = value;
                    this.RaisePropertyChanged("storeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartRecord", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class CartRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime addedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool enabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord uField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime added {
            get {
                return this.addedField;
            }
            set {
                if ((this.addedField.Equals(value) != true)) {
                    this.addedField = value;
                    this.RaisePropertyChanged("added");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cartId {
            get {
                return this.cartIdField;
            }
            set {
                if ((this.cartIdField.Equals(value) != true)) {
                    this.cartIdField = value;
                    this.RaisePropertyChanged("cartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                if ((this.enabledField.Equals(value) != true)) {
                    this.enabledField = value;
                    this.RaisePropertyChanged("enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord p {
            get {
                return this.pField;
            }
            set {
                if ((object.ReferenceEquals(this.pField, value) != true)) {
                    this.pField = value;
                    this.RaisePropertyChanged("p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodId {
            get {
                return this.prodIdField;
            }
            set {
                if ((this.prodIdField.Equals(value) != true)) {
                    this.prodIdField = value;
                    this.RaisePropertyChanged("prodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord u {
            get {
                return this.uField;
            }
            set {
                if ((object.ReferenceEquals(this.uField, value) != true)) {
                    this.uField = value;
                    this.RaisePropertyChanged("u");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRESQSERVICE")]
    public interface IRESQSERVICE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/loginUser", ReplyAction="http://tempuri.org/IRESQSERVICE/loginUserResponse")]
        int loginUser(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/loginUser", ReplyAction="http://tempuri.org/IRESQSERVICE/loginUserResponse")]
        System.Threading.Tasks.Task<int> loginUserAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/regAdminResponse")]
        bool regAdmin(string uEmail, string uPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/regAdminResponse")]
        System.Threading.Tasks.Task<bool> regAdminAsync(string uEmail, string uPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regCust", ReplyAction="http://tempuri.org/IRESQSERVICE/regCustResponse")]
        bool regCust(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regCust", ReplyAction="http://tempuri.org/IRESQSERVICE/regCustResponse")]
        System.Threading.Tasks.Task<bool> regCustAsync(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regStore", ReplyAction="http://tempuri.org/IRESQSERVICE/regStoreResponse")]
        bool regStore(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regStore", ReplyAction="http://tempuri.org/IRESQSERVICE/regStoreResponse")]
        System.Threading.Tasks.Task<bool> regStoreAsync(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/getAdminResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord getAdmin(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/getAdminResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord> getAdminAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getCustomer", ReplyAction="http://tempuri.org/IRESQSERVICE/getCustomerResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CustomerRecord getCustomer(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getCustomer", ReplyAction="http://tempuri.org/IRESQSERVICE/getCustomerResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CustomerRecord> getCustomerAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getStore", ReplyAction="http://tempuri.org/IRESQSERVICE/getStoreResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.StoreRecord getStore(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getStore", ReplyAction="http://tempuri.org/IRESQSERVICE/getStoreResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.StoreRecord> getStoreAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetEmployeeRecords", ReplyAction="http://tempuri.org/IRESQSERVICE/GetEmployeeRecordsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[] GetEmployeeRecords(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetEmployeeRecords", ReplyAction="http://tempuri.org/IRESQSERVICE/GetEmployeeRecordsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[]> GetEmployeeRecordsAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/DeleteUser", ReplyAction="http://tempuri.org/IRESQSERVICE/DeleteUserResponse")]
        string DeleteUser(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/DeleteUser", ReplyAction="http://tempuri.org/IRESQSERVICE/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/SearchUser", ReplyAction="http://tempuri.org/IRESQSERVICE/SearchUserResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[] SearchUser(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/SearchUser", ReplyAction="http://tempuri.org/IRESQSERVICE/SearchUserResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[]> SearchUserAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/UpdateUser", ReplyAction="http://tempuri.org/IRESQSERVICE/UpdateUserResponse")]
        string UpdateUser(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/UpdateUser", ReplyAction="http://tempuri.org/IRESQSERVICE/UpdateUserResponse")]
        System.Threading.Tasks.Task<string> UpdateUserAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAllProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/getAllProductsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAllProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/getAllProductsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/SearchProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/SearchProductsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[] SearchProducts(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/SearchProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/SearchProductsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[]> SearchProductsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/AddProductResponse")]
        bool AddProduct(int sID, string name, string desc, double price, string picPath, System.DateTime date, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(int sID, string name, string desc, double price, string picPath, System.DateTime date, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddToCart", ReplyAction="http://tempuri.org/IRESQSERVICE/AddToCartResponse")]
        bool AddToCart(int pID, int uID, System.DateTime added, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddToCart", ReplyAction="http://tempuri.org/IRESQSERVICE/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int pID, int uID, System.DateTime added, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetCart", ReplyAction="http://tempuri.org/IRESQSERVICE/GetCartResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CartRecord[] GetCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetCart", ReplyAction="http://tempuri.org/IRESQSERVICE/GetCartResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CartRecord[]> GetCartAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESQSERVICEChannel : Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.IRESQSERVICE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESQSERVICEClient : System.ServiceModel.ClientBase<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.IRESQSERVICE>, Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.IRESQSERVICE {
        
        public RESQSERVICEClient() {
        }
        
        public RESQSERVICEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESQSERVICEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESQSERVICEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESQSERVICEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int loginUser(string user, string pass) {
            return base.Channel.loginUser(user, pass);
        }
        
        public System.Threading.Tasks.Task<int> loginUserAsync(string user, string pass) {
            return base.Channel.loginUserAsync(user, pass);
        }
        
        public bool regAdmin(string uEmail, string uPass) {
            return base.Channel.regAdmin(uEmail, uPass);
        }
        
        public System.Threading.Tasks.Task<bool> regAdminAsync(string uEmail, string uPass) {
            return base.Channel.regAdminAsync(uEmail, uPass);
        }
        
        public bool regCust(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant) {
            return base.Channel.regCust(uEmail, uPass, fName, lName, BDate, grant);
        }
        
        public System.Threading.Tasks.Task<bool> regCustAsync(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant) {
            return base.Channel.regCustAsync(uEmail, uPass, fName, lName, BDate, grant);
        }
        
        public bool regStore(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type) {
            return base.Channel.regStore(uEmail, uPass, comp, name, icoPath, loc, type);
        }
        
        public System.Threading.Tasks.Task<bool> regStoreAsync(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type) {
            return base.Channel.regStoreAsync(uEmail, uPass, comp, name, icoPath, loc, type);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord getAdmin(string uEmail) {
            return base.Channel.getAdmin(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord> getAdminAsync(string uEmail) {
            return base.Channel.getAdminAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CustomerRecord getCustomer(string uEmail) {
            return base.Channel.getCustomer(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CustomerRecord> getCustomerAsync(string uEmail) {
            return base.Channel.getCustomerAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.StoreRecord getStore(string uEmail) {
            return base.Channel.getStore(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.StoreRecord> getStoreAsync(string uEmail) {
            return base.Channel.getStoreAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[] GetEmployeeRecords(string uEmail) {
            return base.Channel.GetEmployeeRecords(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[]> GetEmployeeRecordsAsync(string uEmail) {
            return base.Channel.GetEmployeeRecordsAsync(uEmail);
        }
        
        public string DeleteUser(string uEmail) {
            return base.Channel.DeleteUser(uEmail);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(string uEmail) {
            return base.Channel.DeleteUserAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[] SearchUser(string uEmail) {
            return base.Channel.SearchUser(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.UserRecord[]> SearchUserAsync(string uEmail) {
            return base.Channel.SearchUserAsync(uEmail);
        }
        
        public string UpdateUser(string uEmail) {
            return base.Channel.UpdateUser(uEmail);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserAsync(string uEmail) {
            return base.Channel.UpdateUserAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[] SearchProducts(string name) {
            return base.Channel.SearchProducts(name);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.ProductRecord[]> SearchProductsAsync(string name) {
            return base.Channel.SearchProductsAsync(name);
        }
        
        public bool AddProduct(int sID, string name, string desc, double price, string picPath, System.DateTime date, bool enabled) {
            return base.Channel.AddProduct(sID, name, desc, price, picPath, date, enabled);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(int sID, string name, string desc, double price, string picPath, System.DateTime date, bool enabled) {
            return base.Channel.AddProductAsync(sID, name, desc, price, picPath, date, enabled);
        }
        
        public bool AddToCart(int pID, int uID, System.DateTime added, bool enabled) {
            return base.Channel.AddToCart(pID, uID, added, enabled);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int pID, int uID, System.DateTime added, bool enabled) {
            return base.Channel.AddToCartAsync(pID, uID, added, enabled);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CartRecord[] GetCart() {
            return base.Channel.GetCart();
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ServiceReference1.CartRecord[]> GetCartAsync() {
            return base.Channel.GetCartAsync();
        }
    }
}
