//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team34_GP_IFM02B2_2023_WebApp.ResQReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTable", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class UserTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashedPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashedPassword {
            get {
                return this.HashedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashedPasswordField, value) != true)) {
                    this.HashedPasswordField = value;
                    this.RaisePropertyChanged("HashedPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] CartItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.FavouriteStore[] FavouriteStoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GrantRecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.FavouriteStore[] FavouriteStores {
            get {
                return this.FavouriteStoresField;
            }
            set {
                if ((object.ReferenceEquals(this.FavouriteStoresField, value) != true)) {
                    this.FavouriteStoresField = value;
                    this.RaisePropertyChanged("FavouriteStores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GrantRecipient {
            get {
                return this.GrantRecipientField;
            }
            set {
                if ((this.GrantRecipientField.Equals(value) != true)) {
                    this.GrantRecipientField = value;
                    this.RaisePropertyChanged("GrantRecipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.FavouriteStore[] FavouriteStoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable UserTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.FavouriteStore[] FavouriteStores {
            get {
                return this.FavouriteStoresField;
            }
            set {
                if ((object.ReferenceEquals(this.FavouriteStoresField, value) != true)) {
                    this.FavouriteStoresField = value;
                    this.RaisePropertyChanged("FavouriteStores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreType {
            get {
                return this.StoreTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreTypeField, value) != true)) {
                    this.StoreTypeField = value;
                    this.RaisePropertyChanged("StoreType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((this.CartIdField.Equals(value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FavouriteStore", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class FavouriteStore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FavStoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerUserId {
            get {
                return this.CustomerUserIdField;
            }
            set {
                if ((this.CustomerUserIdField.Equals(value) != true)) {
                    this.CustomerUserIdField = value;
                    this.RaisePropertyChanged("CustomerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FavStoreId {
            get {
                return this.FavStoreIdField;
            }
            set {
                if ((this.FavStoreIdField.Equals(value) != true)) {
                    this.FavStoreIdField = value;
                    this.RaisePropertyChanged("FavStoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreUserId {
            get {
                return this.StoreUserIdField;
            }
            set {
                if ((this.StoreUserIdField.Equals(value) != true)) {
                    this.StoreUserIdField = value;
                    this.RaisePropertyChanged("StoreUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[] InvoiceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[] InvoiceItems {
            get {
                return this.InvoiceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceItemsField, value) != true)) {
                    this.InvoiceItemsField = value;
                    this.RaisePropertyChanged("InvoiceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] CartItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[] InvoiceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.ProductTag[] ProductTagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] CartItems {
            get {
                return this.CartItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.CartItemsField, value) != true)) {
                    this.CartItemsField = value;
                    this.RaisePropertyChanged("CartItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[] InvoiceItems {
            get {
                return this.InvoiceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceItemsField, value) != true)) {
                    this.InvoiceItemsField = value;
                    this.RaisePropertyChanged("InvoiceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.ProductTag[] ProductTags {
            get {
                return this.ProductTagsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTagsField, value) != true)) {
                    this.ProductTagsField = value;
                    this.RaisePropertyChanged("ProductTags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceItem", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class InvoiceItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceItemId {
            get {
                return this.InvoiceItemIdField;
            }
            set {
                if ((this.InvoiceItemIdField.Equals(value) != true)) {
                    this.InvoiceItemIdField = value;
                    this.RaisePropertyChanged("InvoiceItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductTag", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class ProductTag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductTagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.Tag TagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TagIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTagId {
            get {
                return this.ProductTagIdField;
            }
            set {
                if ((this.ProductTagIdField.Equals(value) != true)) {
                    this.ProductTagIdField = value;
                    this.RaisePropertyChanged("ProductTagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Tag Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TagId {
            get {
                return this.TagIdField;
            }
            set {
                if ((this.TagIdField.Equals(value) != true)) {
                    this.TagIdField = value;
                    this.RaisePropertyChanged("TagId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/Team34_GP_IFM02B2_2023_WCF")]
    [System.SerializableAttribute()]
    public partial class Tag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Team34_GP_IFM02B2_2023_WebApp.ResQReference.ProductTag[] ProductTagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TagIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.ProductTag[] ProductTags {
            get {
                return this.ProductTagsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTagsField, value) != true)) {
                    this.ProductTagsField = value;
                    this.RaisePropertyChanged("ProductTags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TagID {
            get {
                return this.TagIDField;
            }
            set {
                if ((this.TagIDField.Equals(value) != true)) {
                    this.TagIDField = value;
                    this.RaisePropertyChanged("TagID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResQReference.IRESQSERVICE")]
    public interface IRESQSERVICE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/loginUser", ReplyAction="http://tempuri.org/IRESQSERVICE/loginUserResponse")]
        int loginUser(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/loginUser", ReplyAction="http://tempuri.org/IRESQSERVICE/loginUserResponse")]
        System.Threading.Tasks.Task<int> loginUserAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/regAdminResponse")]
        bool regAdmin(string uEmail, string uPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/regAdminResponse")]
        System.Threading.Tasks.Task<bool> regAdminAsync(string uEmail, string uPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regCust", ReplyAction="http://tempuri.org/IRESQSERVICE/regCustResponse")]
        bool regCust(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regCust", ReplyAction="http://tempuri.org/IRESQSERVICE/regCustResponse")]
        System.Threading.Tasks.Task<bool> regCustAsync(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regStore", ReplyAction="http://tempuri.org/IRESQSERVICE/regStoreResponse")]
        bool regStore(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/regStore", ReplyAction="http://tempuri.org/IRESQSERVICE/regStoreResponse")]
        System.Threading.Tasks.Task<bool> regStoreAsync(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/getAdminResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable getAdmin(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAdmin", ReplyAction="http://tempuri.org/IRESQSERVICE/getAdminResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable> getAdminAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getUser", ReplyAction="http://tempuri.org/IRESQSERVICE/getUserResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable getUser(string uEmail, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getUser", ReplyAction="http://tempuri.org/IRESQSERVICE/getUserResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable> getUserAsync(string uEmail, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getCustomer", ReplyAction="http://tempuri.org/IRESQSERVICE/getCustomerResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer getCustomer(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getCustomer", ReplyAction="http://tempuri.org/IRESQSERVICE/getCustomerResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer> getCustomerAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getStore", ReplyAction="http://tempuri.org/IRESQSERVICE/getStoreResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store getStore(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getStore", ReplyAction="http://tempuri.org/IRESQSERVICE/getStoreResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store> getStoreAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getStores", ReplyAction="http://tempuri.org/IRESQSERVICE/getStoresResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store[] getStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getStores", ReplyAction="http://tempuri.org/IRESQSERVICE/getStoresResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store[]> getStoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetEmployeeRecords", ReplyAction="http://tempuri.org/IRESQSERVICE/GetEmployeeRecordsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable[] GetEmployeeRecords(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetEmployeeRecords", ReplyAction="http://tempuri.org/IRESQSERVICE/GetEmployeeRecordsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable[]> GetEmployeeRecordsAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAllProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/getAllProductsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getAllProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/getAllProductsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/SearchProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/SearchProductsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] SearchProducts(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/SearchProducts", ReplyAction="http://tempuri.org/IRESQSERVICE/SearchProductsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[]> SearchProductsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/AddProductResponse")]
        bool AddProduct(int sID, string name, string desc, int quant, double price, string picPath, System.DateTime date, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(int sID, string name, string desc, int quant, double price, string picPath, System.DateTime date, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddToCart", ReplyAction="http://tempuri.org/IRESQSERVICE/AddToCartResponse")]
        bool AddToCart(int pID, int uID, System.DateTime added, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/AddToCart", ReplyAction="http://tempuri.org/IRESQSERVICE/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int pID, int uID, System.DateTime added, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetCart", ReplyAction="http://tempuri.org/IRESQSERVICE/GetCartResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] GetCart(int UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/GetCart", ReplyAction="http://tempuri.org/IRESQSERVICE/GetCartResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[]> GetCartAsync(int UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/editProductResponse")]
        bool editProduct(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product P);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/editProductResponse")]
        System.Threading.Tasks.Task<bool> editProductAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product P);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editUser", ReplyAction="http://tempuri.org/IRESQSERVICE/editUserResponse")]
        bool editUser(Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editUser", ReplyAction="http://tempuri.org/IRESQSERVICE/editUserResponse")]
        System.Threading.Tasks.Task<bool> editUserAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable U);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editCustomer", ReplyAction="http://tempuri.org/IRESQSERVICE/editCustomerResponse")]
        bool editCustomer(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editCustomer", ReplyAction="http://tempuri.org/IRESQSERVICE/editCustomerResponse")]
        System.Threading.Tasks.Task<bool> editCustomerAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editStore", ReplyAction="http://tempuri.org/IRESQSERVICE/editStoreResponse")]
        bool editStore(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store S);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/editStore", ReplyAction="http://tempuri.org/IRESQSERVICE/editStoreResponse")]
        System.Threading.Tasks.Task<bool> editStoreAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store S);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/addInvoice", ReplyAction="http://tempuri.org/IRESQSERVICE/addInvoiceResponse")]
        bool addInvoice(int UID, double price, System.DateTime TOS, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/addInvoice", ReplyAction="http://tempuri.org/IRESQSERVICE/addInvoiceResponse")]
        System.Threading.Tasks.Task<bool> addInvoiceAsync(int UID, double price, System.DateTime TOS, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/addInvoiceItem", ReplyAction="http://tempuri.org/IRESQSERVICE/addInvoiceItemResponse")]
        bool addInvoiceItem(int ID, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/addInvoiceItem", ReplyAction="http://tempuri.org/IRESQSERVICE/addInvoiceItemResponse")]
        System.Threading.Tasks.Task<bool> addInvoiceItemAsync(int ID, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getFilteredList", ReplyAction="http://tempuri.org/IRESQSERVICE/getFilteredListResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] getFilteredList(string name, double P1, double P2, int tag, int manu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getFilteredList", ReplyAction="http://tempuri.org/IRESQSERVICE/getFilteredListResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[]> getFilteredListAsync(string name, double P1, double P2, int tag, int manu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getInvoices", ReplyAction="http://tempuri.org/IRESQSERVICE/getInvoicesResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice[] getInvoices(int UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getInvoices", ReplyAction="http://tempuri.org/IRESQSERVICE/getInvoicesResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice[]> getInvoicesAsync(int UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getInvoice", ReplyAction="http://tempuri.org/IRESQSERVICE/getInvoiceResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice getInvoice(int IID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getInvoice", ReplyAction="http://tempuri.org/IRESQSERVICE/getInvoiceResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice> getInvoiceAsync(int IID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getInvoiceItems", ReplyAction="http://tempuri.org/IRESQSERVICE/getInvoiceItemsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[] getInvoiceItems(int IID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getInvoiceItems", ReplyAction="http://tempuri.org/IRESQSERVICE/getInvoiceItemsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[]> getInvoiceItemsAsync(int IID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/getProductResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product getProduct(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getProduct", ReplyAction="http://tempuri.org/IRESQSERVICE/getProductResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product> getProductAsync(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getTags", ReplyAction="http://tempuri.org/IRESQSERVICE/getTagsResponse")]
        Team34_GP_IFM02B2_2023_WebApp.ResQReference.Tag[] getTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESQSERVICE/getTags", ReplyAction="http://tempuri.org/IRESQSERVICE/getTagsResponse")]
        System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Tag[]> getTagsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESQSERVICEChannel : Team34_GP_IFM02B2_2023_WebApp.ResQReference.IRESQSERVICE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESQSERVICEClient : System.ServiceModel.ClientBase<Team34_GP_IFM02B2_2023_WebApp.ResQReference.IRESQSERVICE>, Team34_GP_IFM02B2_2023_WebApp.ResQReference.IRESQSERVICE {
        
        public RESQSERVICEClient() {
        }
        
        public RESQSERVICEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESQSERVICEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESQSERVICEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESQSERVICEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int loginUser(string user, string pass) {
            return base.Channel.loginUser(user, pass);
        }
        
        public System.Threading.Tasks.Task<int> loginUserAsync(string user, string pass) {
            return base.Channel.loginUserAsync(user, pass);
        }
        
        public bool regAdmin(string uEmail, string uPass) {
            return base.Channel.regAdmin(uEmail, uPass);
        }
        
        public System.Threading.Tasks.Task<bool> regAdminAsync(string uEmail, string uPass) {
            return base.Channel.regAdminAsync(uEmail, uPass);
        }
        
        public bool regCust(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant) {
            return base.Channel.regCust(uEmail, uPass, fName, lName, BDate, grant);
        }
        
        public System.Threading.Tasks.Task<bool> regCustAsync(string uEmail, string uPass, string fName, string lName, System.DateTime BDate, bool grant) {
            return base.Channel.regCustAsync(uEmail, uPass, fName, lName, BDate, grant);
        }
        
        public bool regStore(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type) {
            return base.Channel.regStore(uEmail, uPass, comp, name, icoPath, loc, type);
        }
        
        public System.Threading.Tasks.Task<bool> regStoreAsync(string uEmail, string uPass, string comp, string name, string icoPath, string loc, string type) {
            return base.Channel.regStoreAsync(uEmail, uPass, comp, name, icoPath, loc, type);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable getAdmin(string uEmail) {
            return base.Channel.getAdmin(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable> getAdminAsync(string uEmail) {
            return base.Channel.getAdminAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable getUser(string uEmail, int type) {
            return base.Channel.getUser(uEmail, type);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable> getUserAsync(string uEmail, int type) {
            return base.Channel.getUserAsync(uEmail, type);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer getCustomer(string uEmail) {
            return base.Channel.getCustomer(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer> getCustomerAsync(string uEmail) {
            return base.Channel.getCustomerAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store getStore(string uEmail) {
            return base.Channel.getStore(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store> getStoreAsync(string uEmail) {
            return base.Channel.getStoreAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store[] getStores() {
            return base.Channel.getStores();
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store[]> getStoresAsync() {
            return base.Channel.getStoresAsync();
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable[] GetEmployeeRecords(string uEmail) {
            return base.Channel.GetEmployeeRecords(uEmail);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable[]> GetEmployeeRecordsAsync(string uEmail) {
            return base.Channel.GetEmployeeRecordsAsync(uEmail);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] SearchProducts(string name) {
            return base.Channel.SearchProducts(name);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[]> SearchProductsAsync(string name) {
            return base.Channel.SearchProductsAsync(name);
        }
        
        public bool AddProduct(int sID, string name, string desc, int quant, double price, string picPath, System.DateTime date, bool enabled) {
            return base.Channel.AddProduct(sID, name, desc, quant, price, picPath, date, enabled);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(int sID, string name, string desc, int quant, double price, string picPath, System.DateTime date, bool enabled) {
            return base.Channel.AddProductAsync(sID, name, desc, quant, price, picPath, date, enabled);
        }
        
        public bool AddToCart(int pID, int uID, System.DateTime added, bool enabled) {
            return base.Channel.AddToCart(pID, uID, added, enabled);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int pID, int uID, System.DateTime added, bool enabled) {
            return base.Channel.AddToCartAsync(pID, uID, added, enabled);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] GetCart(int UID) {
            return base.Channel.GetCart(UID);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[]> GetCartAsync(int UID) {
            return base.Channel.GetCartAsync(UID);
        }
        
        public bool editProduct(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product P) {
            return base.Channel.editProduct(P);
        }
        
        public System.Threading.Tasks.Task<bool> editProductAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product P) {
            return base.Channel.editProductAsync(P);
        }
        
        public bool editUser(Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable U) {
            return base.Channel.editUser(U);
        }
        
        public System.Threading.Tasks.Task<bool> editUserAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.UserTable U) {
            return base.Channel.editUserAsync(U);
        }
        
        public bool editCustomer(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer C) {
            return base.Channel.editCustomer(C);
        }
        
        public System.Threading.Tasks.Task<bool> editCustomerAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Customer C) {
            return base.Channel.editCustomerAsync(C);
        }
        
        public bool editStore(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store S) {
            return base.Channel.editStore(S);
        }
        
        public System.Threading.Tasks.Task<bool> editStoreAsync(Team34_GP_IFM02B2_2023_WebApp.ResQReference.Store S) {
            return base.Channel.editStoreAsync(S);
        }
        
        public bool addInvoice(int UID, double price, System.DateTime TOS, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] cart) {
            return base.Channel.addInvoice(UID, price, TOS, cart);
        }
        
        public System.Threading.Tasks.Task<bool> addInvoiceAsync(int UID, double price, System.DateTime TOS, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem[] cart) {
            return base.Channel.addInvoiceAsync(UID, price, TOS, cart);
        }
        
        public bool addInvoiceItem(int ID, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem c) {
            return base.Channel.addInvoiceItem(ID, c);
        }
        
        public System.Threading.Tasks.Task<bool> addInvoiceItemAsync(int ID, Team34_GP_IFM02B2_2023_WebApp.ResQReference.CartItem c) {
            return base.Channel.addInvoiceItemAsync(ID, c);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[] getFilteredList(string name, double P1, double P2, int tag, int manu) {
            return base.Channel.getFilteredList(name, P1, P2, tag, manu);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product[]> getFilteredListAsync(string name, double P1, double P2, int tag, int manu) {
            return base.Channel.getFilteredListAsync(name, P1, P2, tag, manu);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice[] getInvoices(int UID) {
            return base.Channel.getInvoices(UID);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice[]> getInvoicesAsync(int UID) {
            return base.Channel.getInvoicesAsync(UID);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice getInvoice(int IID) {
            return base.Channel.getInvoice(IID);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Invoice> getInvoiceAsync(int IID) {
            return base.Channel.getInvoiceAsync(IID);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[] getInvoiceItems(int IID) {
            return base.Channel.getInvoiceItems(IID);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.InvoiceItem[]> getInvoiceItemsAsync(int IID) {
            return base.Channel.getInvoiceItemsAsync(IID);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product getProduct(int pID) {
            return base.Channel.getProduct(pID);
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Product> getProductAsync(int pID) {
            return base.Channel.getProductAsync(pID);
        }
        
        public Team34_GP_IFM02B2_2023_WebApp.ResQReference.Tag[] getTags() {
            return base.Channel.getTags();
        }
        
        public System.Threading.Tasks.Task<Team34_GP_IFM02B2_2023_WebApp.ResQReference.Tag[]> getTagsAsync() {
            return base.Channel.getTagsAsync();
        }
    }
}
